version: "3.8"

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  publisher:
    image: publisher
    build:
      context: ./publisher
      dockerfile: Dockerfile
    depends_on:
      - redis

  subscriber:
    image: subscriber
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    depends_on:
      - redis

  logger:
    image: logger-service
    build:
      context: ./logger-service
      dockerfile: Dockerfile
    depends_on:
      - redis
